#!/usr/bin/env python3
"""Embed processed chunks into a persistent ChromaDB vector store.

Reads the chunks JSON produced by process-corpus.py, generates embeddings
using a sentence-transformers model, and stores them in a ChromaDB
collection on disk.

Each chunk is stored with:
  - document: the body text (what gets embedded and returned at query time)
  - embedding: generated by the sentence-transformers model
  - metadata: source_url, source_title, heading_text, heading_path,
               heading_level, chunk_index, chunk_total, content_type
  - id: a stable deterministic ID derived from source_url + heading + chunk_index

The collection persists to disk at --db-dir and can be queried by
subsequent pipeline stages without re-embedding.

Re-running this script against the same chunks file is safe: existing
documents are updated in place via upsert, so you can re-embed after
adjusting chunking parameters without having to wipe the database.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import sys
from pathlib import Path

import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DEFAULT_MODEL = "multi-qa-mpnet-base-dot-v1"
DEFAULT_DB_DIR = Path("data/horatio/chroma")
DEFAULT_COLLECTION = "scc-docs"

# ChromaDB upsert works in batches; large single calls can be slow or fail.
DEFAULT_BATCH_SIZE = 50


# ---------------------------------------------------------------------------
# ID generation
# ---------------------------------------------------------------------------

def make_chunk_id(chunk: dict) -> str:
    """Generate a stable, deterministic ID for a chunk.

    Derived from source URL + heading path + heading text + chunk index.
    heading_path is included because a single page can contain multiple
    sections with identical heading text at different hierarchy levels
    (e.g. nested "Before you begin" / "Procedure" sections in DITA),
    which would otherwise produce duplicate IDs.
    """
    path_str = " | ".join(chunk["heading_path"])
    key = f"{chunk['source_url']}::{path_str}::{chunk['heading_text']}::{chunk['chunk_index']}"
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:32]


# ---------------------------------------------------------------------------
# Metadata serialisation
# ---------------------------------------------------------------------------

def make_metadata(chunk: dict) -> dict:
    """Extract ChromaDB-compatible metadata from a chunk.

    ChromaDB metadata values must be str, int, float, or bool.
    heading_path is a list, so it's serialised to a pipe-delimited string.
    """
    return {
        "source_url": chunk["source_url"],
        "source_title": chunk["source_title"],
        "heading_text": chunk["heading_text"],
        # heading_path as pipe-delimited string; deserialise by splitting on " | "
        "heading_path": " | ".join(chunk["heading_path"]),
        "heading_level": chunk["heading_level"],
        "chunk_index": chunk["chunk_index"],
        "chunk_total": chunk["chunk_total"],
        "content_type": chunk["content_type"],
    }


# ---------------------------------------------------------------------------
# Batched upsert
# ---------------------------------------------------------------------------

def upsert_chunks(
    collection: chromadb.Collection,
    chunks: list[dict],
    batch_size: int,
) -> None:
    """Upsert all chunks into the collection in batches."""
    total = len(chunks)
    for start in range(0, total, batch_size):
        batch = chunks[start : start + batch_size]
        end = min(start + batch_size, total)

        ids = [make_chunk_id(c) for c in batch]
        documents = [c["body"] for c in batch]
        metadatas = [make_metadata(c) for c in batch]

        collection.upsert(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
        )
        print(f"  Upserted {end}/{total} chunks...", flush=True)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def verify_collection(collection: chromadb.Collection, sample_query: str) -> None:
    """Run a sample query and print results to confirm the store is working."""
    print(f"\nVerification query: {repr(sample_query)}")
    results = collection.query(
        query_texts=[sample_query],
        n_results=3,
        include=["documents", "metadatas", "distances"],
    )
    docs = results["documents"][0]
    metas = results["metadatas"][0]
    distances = results["distances"][0]

    for i, (doc, meta, dist) in enumerate(zip(docs, metas, distances)):
        path = meta.get("heading_path", "")
        heading = meta.get("heading_text", "")
        full_path = f"{path} | {heading}" if path else heading
        print(f"\n  Result {i+1} (distance: {dist:.4f})")
        print(f"  Path:   {full_path}")
        print(f"  Source: {meta.get('source_title', '')}")
        print(f"  URL:    {meta.get('source_url', '')}")
        print(f"  Body:   {doc[:120]}...")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Embed processed Horatio chunks into a persistent ChromaDB "
            "vector store using a sentence-transformers model."
        )
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Path to the chunks JSON produced by process-corpus.py",
    )
    parser.add_argument(
        "--db-dir",
        type=Path,
        default=DEFAULT_DB_DIR,
        help=f"Directory for the persistent ChromaDB store (default: {DEFAULT_DB_DIR})",
    )
    parser.add_argument(
        "--collection",
        type=str,
        default=DEFAULT_COLLECTION,
        help=f"ChromaDB collection name (default: {DEFAULT_COLLECTION})",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=DEFAULT_MODEL,
        help=f"Sentence-transformers model name (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"Upsert batch size (default: {DEFAULT_BATCH_SIZE})",
    )
    parser.add_argument(
        "--verify",
        type=str,
        default="How do I create a new organization?",
        help=(
            "Sample query to run after embedding to verify the store is working. "
            "Set to empty string to skip verification."
        ),
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    args = parse_args()

    if not args.input.exists():
        print(f"Input file not found: {args.input}", file=sys.stderr)
        return 2

    print(f"Reading chunks: {args.input}", flush=True)
    data = json.loads(args.input.read_text(encoding="utf-8"))
    chunks = data["chunks"]
    print(f"Loaded {len(chunks)} chunks from {data.get('root_url', 'unknown source')}")

    # --- Initialise embedding function ---
    print(f"\nLoading embedding model: {args.model}")
    print("(First run downloads model weights — this may take a minute.)")
    embedding_fn = SentenceTransformerEmbeddingFunction(
        model_name=args.model,
        device="cpu",
        normalize_embeddings=True,
    )

    # --- Initialise ChromaDB ---
    args.db_dir.mkdir(parents=True, exist_ok=True)
    print(f"\nOpening ChromaDB at: {args.db_dir}")
    client = chromadb.PersistentClient(path=str(args.db_dir))

    collection = client.get_or_create_collection(
        name=args.collection,
        embedding_function=embedding_fn,
        metadata={
            "model": args.model,
            "source": str(args.input),
            "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
            "hnsw:space": "cosine",
        },
    )

    existing_count = collection.count()
    if existing_count > 0:
        print(
            f"Collection '{args.collection}' already contains {existing_count} documents. "
            "Upserting (existing documents will be updated)."
        )

    # --- Embed and upsert ---
    print(f"\nEmbedding and upserting {len(chunks)} chunks...")
    started = dt.datetime.now()
    upsert_chunks(collection, chunks, args.batch_size)
    elapsed = (dt.datetime.now() - started).total_seconds()

    final_count = collection.count()
    print(f"\nDone. {final_count} documents in collection '{args.collection}'.")
    print(f"Elapsed: {elapsed:.1f}s  ({elapsed/len(chunks):.2f}s per chunk)")
    print(f"ChromaDB persisted at: {args.db_dir}")

    # --- Verify ---
    if args.verify:
        verify_collection(collection, args.verify)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())